"""Add tenant_id

Revision ID: 5e134fbfd930
Revises: 001_initial
Create Date: 2026-08-22 11:06:58.159031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e134fbfd930'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.add_column('customers', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'tenants', ['tenant_id'], ['id'])
    op.add_column('inventory_logs', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_inventory_logs_tenant_id'), 'inventory_logs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'inventory_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('products', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'])
    op.add_column('sales', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_column('sales', 'tenant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'inventory_logs', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_logs_tenant_id'), table_name='inventory_logs')
    op.drop_column('inventory_logs', 'tenant_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_column('customers', 'tenant_id')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
