"""add status to tenants

Revision ID: 760a349769b5
Revises: 5e134fbfd930
Create Date: 2026-08-28 23:23:55.258307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760a349769b5'
down_revision = '5e134fbfd930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('size', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('is_reverted', sa.Boolean(), nullable=False))
    op.add_column('tenants', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tenants', 'status')
    op.drop_column('sales', 'is_reverted')
    op.drop_column('sale_items', 'size')
    # ### end Alembic commands ###
